repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        types: [python]
-   repo: https://github.com/miki725/importanize/
    rev: '0.8.0-alpha2'
    hooks:
    -   id: importanize
        args: [--verbose]
